package examen2prograii_carlosnoé;

import java.util.ArrayList;

public class Principality extends javax.swing.JFrame {

    static ArrayList<Torneo> Equipos;

    public void ArActu() {
        javax.swing.tree.DefaultMutableTreeNode treeNode0 = new javax.swing.tree.DefaultMutableTreeNode("Torneos");
        JtreeDPs.setModel(new javax.swing.tree.DefaultTreeModel(treeNode0));
        javax.swing.tree.DefaultMutableTreeNode treeNode1 = new javax.swing.tree.DefaultMutableTreeNode("Q1");
        treeNode0.add(treeNode1);
        javax.swing.tree.DefaultMutableTreeNode treeNode2 = new javax.swing.tree.DefaultMutableTreeNode("Q2");
        treeNode0.add(treeNode2);
        javax.swing.tree.DefaultMutableTreeNode treeNode4 = new javax.swing.tree.DefaultMutableTreeNode("Q4");
        treeNode0.add(treeNode4);
        javax.swing.tree.DefaultMutableTreeNode treeNode5 = new javax.swing.tree.DefaultMutableTreeNode("Q5");
        treeNode0.add(treeNode5);

        for (Torneo MODS : Equipos) {
            if (MODS.getPeriodoRZ().equalsIgnoreCase("Q1")) {
                javax.swing.tree.DefaultMutableTreeNode treeNode = new javax.swing.tree.DefaultMutableTreeNode(MODS.getNombre());
                treeNode1.add(treeNode);
            } else if (MODS.getPeriodoRZ().equalsIgnoreCase("Q2")) {
                javax.swing.tree.DefaultMutableTreeNode treeNode = new javax.swing.tree.DefaultMutableTreeNode(MODS.getNombre());
                treeNode2.add(treeNode);
            } else if (MODS.getPeriodoRZ().equalsIgnoreCase("Q4")) {
                javax.swing.tree.DefaultMutableTreeNode treeNode = new javax.swing.tree.DefaultMutableTreeNode(MODS.getNombre());
                treeNode4.add(treeNode);
            } else if (MODS.getPeriodoRZ().equalsIgnoreCase("Q5")) {
                javax.swing.tree.DefaultMutableTreeNode treeNode = new javax.swing.tree.DefaultMutableTreeNode(MODS.getNombre());
                treeNode5.add(treeNode);
            }

        }
    }

    public Principality() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        FramePPrincipality = new javax.swing.JFrame();
        BB = new javax.swing.JPanel();
        TablasDeDeporte = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        JtreeDPs = new javax.swing.JTree();

        BB.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jScrollPane1.setViewportView(JtreeDPs);

        javax.swing.GroupLayout TablasDeDeporteLayout = new javax.swing.GroupLayout(TablasDeDeporte);
        TablasDeDeporte.setLayout(TablasDeDeporteLayout);
        TablasDeDeporteLayout.setHorizontalGroup(
            TablasDeDeporteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 470, Short.MAX_VALUE)
        );
        TablasDeDeporteLayout.setVerticalGroup(
            TablasDeDeporteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 640, Short.MAX_VALUE)
        );

        BB.add(TablasDeDeporte, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 470, 640));

        javax.swing.GroupLayout FramePPrincipalityLayout = new javax.swing.GroupLayout(FramePPrincipality.getContentPane());
        FramePPrincipality.getContentPane().setLayout(FramePPrincipalityLayout);
        FramePPrincipalityLayout.setHorizontalGroup(
            FramePPrincipalityLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(BB, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        FramePPrincipalityLayout.setVerticalGroup(
            FramePPrincipalityLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(BB, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1213, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 640, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principality.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principality.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principality.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principality.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Principality().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel BB;
    private javax.swing.JFrame FramePPrincipality;
    private javax.swing.JTree JtreeDPs;
    private javax.swing.JPanel TablasDeDeporte;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
